name: Go CI

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'go/**'
      - '.github/workflows/go.yml'
  pull_request:
    paths:
      - 'go/**'
      - '.github/workflows/go.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go/go.mod'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Format
        run: make fmt

  release:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go/go.mod'

      - name: Build
        run: make build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: go/bin/zstdseek
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false